otpproject/home/urls.py
from django.urls import path
from .views import home, productlist, productdetail, search, cart, Checkout, add_to_wishlist, wishlist, add_to_cart, remove_from_cart, delete_from_cart, place_order, orders, contact, subscription_email, terms, about

urlpatterns = [
    path('', home, name='home'),
    path('contact/', contact, name='contact'),
    path('subscription-email/', subscription_email, name='subscription_email'),
    path('about/', about, name='about'),
    path('terms/', terms, name='terms'),
    path('products/', productlist, name='products'),
    path('productdetail/<int:id>/', productdetail, name='productdetail'),
    path('search/', search, name='search'),
    path('wishlist/', wishlist, name='wishlist'),
    path('cart/', cart, name='cart'),
    path('checkout/', Checkout.as_view(), name='checkout'),
    path('orders/', orders, name='orders'),
    path('add-to-wishlist/', add_to_wishlist, name='add_to_wishlist'),
    path('add-to-cart/', add_to_cart, name='add_to_cart'),
    path('remove-from-cart/', remove_from_cart, name='remove_from_cart'),
    path('delete-from-cart/', delete_from_cart, name='delete_from_cart'),
    path('place-order/', place_order, name='place_order'),
]

otpproject/otpproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from .sitemaps import StaticSitemap, ProductSitemap
from django.contrib.sitemaps.views import sitemap

sitemaps = {
    'static': StaticSitemap,
    'product':ProductSitemap
}

admin.site.site_header = 'BAKE YUMMY ADMIN'
admin.site.site_title = 'BAKE YUMMY! ADMIN PANEL'
admin.site.index_title = 'WELCOME TO BAKE YUMMY! ADMIN PANEL'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('', include('registration.urls')),
    path('sitemap.xml/', sitemap,{'sitemaps':sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
]

urlpatterns +=static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns +=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

otpproject/home/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.fields import AutoField
from registration.models import Customer
from math import floor
# Create your models here.
class Category(models.Model):
    id = models.AutoField(primary_key=True)
    title = models.CharField(max_length=200)
    slug = models.SlugField()

    def __str__(self):
        return self.title

class Product(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=200)
    desc = models.TextField()
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    weight = models.CharField(max_length=100)
    marked_price = models.FloatField()
    selling_price = models.FloatField()
    available_quantity = models.PositiveIntegerField(default=0) #Remove this default option in the final project
    photo = models.ImageField(upload_to='products/')
    #Char Field For image alt #####-------Needed to be added--------#####
    return_policy = models.CharField(max_length=255)
    slug = models.SlugField()
    tags = models.CharField(max_length=300, default='')
    modified_date = models.DateField(auto_now=True)
    users_wishlist = models.ManyToManyField(User, blank=True, related_name='user_wishlist')

    def __str__(self):
        return self.name + '......'+self.weight

    @property
    def discount_percent(self):
        discount = (self.marked_price - self.selling_price)/self.marked_price
        return str(floor(discount * 100))

class MyCart(models.Model):
    id = models.AutoField(primary_key=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=1)
    date_created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return str(self.id)

    @property
    def sub_total(self):
        return str(self.quantity * self.product.selling_price)

STATUS_CHOICES = (
    ('pending', 'pending'),
    ('received', 'received'),
    ('packed', 'packed'),
    ('on_the_way', 'on_the_way'),
    ('delivered', 'delivered'),
    ('cancel', 'cancel'),
)

class OrderPlaced(models.Model):
    id = models.AutoField(primary_key=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    customer = models.ForeignKey(Customer, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=1)
    total_price = models.PositiveBigIntegerField(default=0)
    ordered_date = models.DateTimeField(auto_now_add=True)
    order_status = models.CharField(max_length=20, choices=STATUS_CHOICES, default='pending')
    ##--------------For Payment Integration--------------##
    #Payment_Method_Choices_Char_Field
    #Payment_Completed_Boolean_Field

    def __str__(self):
        return str(self.user.username + '      ' + self.customer.full_name + '     ' + self.product.name)

class Contact(models.Model):
    sno = models.AutoField(primary_key=True)
    full_name = models.CharField(max_length=50)
    email = models.EmailField(max_length=100)
    message = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return str(self.message[0:15] + '...' + '    By   ' + self.full_name)

class SubscriptionEmail(models.Model):
    id = models.AutoField(primary_key=True)
    email = models.EmailField(max_length=100)
    subscribed_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return str(self.id) + '.....' + self.email
        

otpproject/home/forms.py
from django import forms
from .models import Contact

class ContactForm(forms.ModelForm):
    class Meta:
        model = Contact
        fields = ['full_name', 'email', 'message']
        labels = {'full_name': 'Your Name', 'email': 'Your Email', 'message': 'Your Message'}

otpproject/home/views.py
from django.shortcuts import render
from .models import Contact, SubscriptionEmail
from .forms import ContactForm
from django.http.response import HttpResponseRedirect, JsonResponse
from django.shortcuts import get_object_or_404, render, redirect
from django.views.decorators.csrf import csrf_exempt
from .models import Product
from django.core.paginator import Paginator
from django.views.generic import View
from registration.forms import CustomerForm
from registration.models import Customer
from .models import MyCart, OrderPlaced
from django.contrib import messages
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
from django.template.loader import render_to_string
from django.core.mail import EmailMultiAlternatives
from django.conf import settings

# Create your views here.


# Create your views here.
def home(request):
    disprod = Product.objects.all().order_by('?')[:8]
    allprod = Product.objects.all().order_by('-id')
    if request.user.is_authenticated:
        products = Product.objects.filter(users_wishlist=request.user)
        wishlistcount = products.count()
        cartprod = MyCart.objects.filter(user=request.user)
        cartprodcount = cartprod.count()
    else:
        wishlistcount = ''
        cartprodcount = ''
    context = {
        'disprod':disprod,
        'allprod':allprod,
        'wishlistcount': wishlistcount,
        'cartprodcount': cartprodcount,
    }
    return render(request, 'home/home.html', context)

def productlist(request):
    sort = request.GET.get('sort', 1)
    sortint = int(sort)
    if sortint == 1:
        allprod = Product.objects.all().order_by('-id')
    elif sortint == 2:
        allprod = Product.objects.all().order_by('selling_price')
    elif sortint == 3:
        allprod = Product.objects.all().order_by('-selling_price')
    else:
        allprod = Product.objects.all().order_by('-id')
    paginator = Paginator(allprod, 8)
    page_number = request.GET.get('page', 1)
    page_obj = paginator.get_page(page_number)
    total_pages = page_obj.paginator.num_pages
    pages = []
    pp = int(page_number) - 2
    p = int(page_number) - 1
    pn = int(page_number)
    n = int(page_number) + 1
    nn = int(page_number) + 2
    set1 = {pp, p, pn, n, nn}
    for i in range(total_pages):
        i+=1
        pages.append(i)
    set2 = set(pages)
    set3 = set1.intersection(set2)
    pagelist = list(set3)
    if request.user.is_authenticated:
        products = Product.objects.filter(users_wishlist=request.user)
        wishlistcount = products.count()
        cartprod = MyCart.objects.filter(user=request.user)
        cartprodcount = cartprod.count()
    else:
        wishlistcount = ''
        cartprodcount = ''
    context = {
        'allprod':page_obj,
        'pagelist':pagelist,
        'currentpage':pn,
        'sortint':sortint,
        'wishlistcount': wishlistcount,
        'cartprodcount': cartprodcount,
    }
    return render(request, 'home/productlist.html', context)

def productdetail(request, id):
    product = Product.objects.get(id=id)
    relatedprod = Product.objects.all().order_by('?')[:4]
    favoritemessage = ''
    if request.user.is_authenticated:
        products = Product.objects.filter(users_wishlist=request.user)
        wishlistcount = products.count()
        cartprod = MyCart.objects.filter(user=request.user)
        cartprodcount = cartprod.count()
        productexists = MyCart.objects.filter(user=request.user, product=product)
        if productexists.exists():
            productincart = 'Yes'
        else:
            productincart = 'No'
        print(productincart)
    else:
        wishlistcount = ''
        cartprodcount = ''
        productincart = ''
    if product.users_wishlist.filter(id=request.user.id).exists():
        favoritemessage = 'Remove From Favorites'
    else:
        favoritemessage = 'Add To Favorites'
    context = {
        'product':product,
        'relatedprod':relatedprod,
        'favoritemessage':favoritemessage,
        'wishlistcount': wishlistcount,
        'cartprodcount': cartprodcount,
        'productincart': productincart
    }
    return render(request, 'home/productdetail.html', context)

def search(request):
    query = request.GET.get('query')
    if request.user.is_authenticated:
        products = Product.objects.filter(users_wishlist=request.user)
        wishlistcount = products.count()
        cartprod = MyCart.objects.filter(user=request.user)
        cartprodcount = cartprod.count()
    else:
        wishlistcount = ''
        cartprodcount = ''
    if len(query) > 30:
        products = Product.objects.none()
    else:
        product1 = Product.objects.filter(name__icontains=query)
        product2 = Product.objects.filter(desc__icontains=query)
        product3 = Product.objects.filter(tags__icontains=query)
        productf = product1.union(product2)
        products = productf.union(product3)
    context = {
        'allprod': products,
        'query':query,
        'wishlistcount': wishlistcount,
        'cartprodcount': cartprodcount,
    }
    return render(request, 'home/search.html', context)

def cart(request):
    otherprod = Product.objects.all().order_by('?')[:4]
    if request.user.is_authenticated:
        products = Product.objects.filter(users_wishlist=request.user)
        wishlistcount = products.count()
        cartprod = MyCart.objects.filter(user=request.user)
        cartprodcount = cartprod.count()
    else:
        wishlistcount = ''
        cartprodcount = ''
        cartprod = ''
    context = {
        'otherprod': otherprod,
        'wishlistcount': wishlistcount,
        'cartprod': cartprod,
        'cartprodcount': cartprodcount,
        }
    return render(request, 'home/cart.html', context)


@method_decorator(login_required, name='dispatch')
class Checkout(View):
    def get(self, request):
        form = CustomerForm()
        customers = Customer.objects.filter(user=request.user)
        if request.user.is_authenticated:
            products = Product.objects.filter(users_wishlist=request.user)
            wishlistcount = products.count()
            cartprod = MyCart.objects.filter(user=request.user)
            cartprodcount = cartprod.count()
        else:
            wishlistcount = ''
            cartprodcount = ''
            cartprod = ''
        return render(request, 'home/checkout.html', {'form':form, 'customers':customers, 'cartprod': cartprod,'wishlistcount': wishlistcount,'cartprodcount': cartprodcount,})

    def post(self, request):
        form = CustomerForm(request.POST)
        user = request.user
        customers = Customer.objects.filter(user=user)
        if request.user.is_authenticated:
            products = Product.objects.filter(users_wishlist=request.user)
            wishlistcount = products.count()
            cartprod = MyCart.objects.filter(user=request.user)
            cartprodcount = cartprod.count()
        else:
            wishlistcount = ''
            cartprodcount = ''
        if form.is_valid():
            full_name = form.cleaned_data['full_name']
            city = form.cleaned_data['city']
            address = form.cleaned_data['address']
            locality = form.cleaned_data['locality']
            phone_no = form.cleaned_data['phone_no']
            house_no = form.cleaned_data['house_no']
            zip_code = form.cleaned_data['zip_code']
            cus = Customer(user=user, full_name=full_name, city=city, address=address, locality=locality, phone_no=phone_no, house_no=house_no, zip_code=zip_code)
            cus.save()
            messages.success(request, 'Address/Customer added successfully!!')
            return redirect('checkout')
        return render(request, 'registration/checkout.html', {'form':form, 'customers':customers,'wishlistcount': wishlistcount,'cartprodcount': cartprodcount,})

@csrf_exempt
def add_to_wishlist(request):
    if request.method == 'POST':
        prod_id = request.POST.get('prod_id', '')
        product = get_object_or_404(Product, id=prod_id)
        message = ''
        if product.users_wishlist.filter(id=request.user.id).exists():
            product.users_wishlist.remove(request.user)
            message = 'removed'
        else:
            product.users_wishlist.add(request.user)
            message = 'added'
        data = {'message': message}
        return JsonResponse(data, safe=False)

def wishlist(request):
    if request.user.is_authenticated:
        products = Product.objects.filter(users_wishlist=request.user)
        wishlistcount = products.count()
        cartprod = MyCart.objects.filter(user=request.user)
        cartprodcount = cartprod.count()
    else:
        wishlistcount = ''
        cartprodcount = ''
        products = ''
    context = {'products':products, 'wishlistcount': wishlistcount, 'cartprodcount':cartprodcount}
    return render(request, 'home/wishlist.html', context)

@csrf_exempt
def add_to_cart(request):
    if request.method == 'POST':
        id = request.POST.get('prod_id')
        quantity = request.POST.get('quantity')
        product = Product.objects.get(id=id)
        user = request.user
        # print(id, product, quantity, user.username)
        mycart, created = MyCart.objects.get_or_create(user=user, product=product)
        if created:
            mycart.quantity = int(quantity)
            print('I am just created')
        else:
            mycart.quantity += 1
            print('I am added')
        mycart.save()
        proqty = mycart.quantity
        print(mycart.quantity)
        selling_price = product.selling_price
        sub_total = proqty * product.selling_price
        print(sub_total)
        cartproduct = [c for c in MyCart.objects.filter(user=request.user)]
        cartproducts = {}
        print(cartproduct)
        for i in range(len(cartproduct)):
            if cartproduct[i].id not in cartproducts.keys():

otpproject/templates/home/about.html
{% extends 'base.html' %}
{% load static %}
{% block title %}About Us | Bake Yummy!{% endblock title %}
{% block maincontent %}
<section class="about">
    <div class="aboutimage">
        <h1>ABOUT US</h1>
    </div>
    <div class="abouttext">
        <p>
            We believe that it should be possible to develop a platform for inexpensive yet effective fashion products for ladies. We specialize in skincare, healthcare products, accessories and fashion products like gadgets and electronics especially curtailed for the needs of ladies. We believe this is not just a business. It is a way to express oneself, to be more confident about oneself and to be more creative about one's beauty through expression. Therefore we are committed to maintain the quality of items we sell through our platform. 
        </p><br>
        <p>
            By providing a high-quality, innovative products friendly to the user and environment we aim to:
        </p><br>
        <ul class="points">
            <li>Take over the leading market position in the segment of cosmetic care.</li>
            <li>To become the first choice of end users as well as professional users</li>
            <li>Increase our market share and corporate reputation in new and existing markets.</li>
        </ul>
    </div>
</section>
{% endblock maincontent %}

otpproject/templates/home/cart.html
{% extends 'base.html' %}
{% load static %}
{% block title %}My Cart{% endblock title %}
{% block maincontent %}
<div class="container cart">
    <table>
      <tr id='carttablerow'>
        <th>Product</th>
        <th>Quantity</th>
        <th>Subtotal</th>
      </tr>
      {% if cartprod %}
      {% for c in cartprod %}
      <tr data-table-id = '{{c.product.id}}' data-table-url = '{% url "delete_from_cart" %}' class='datatableid{{c.product.id}}' id='carttablerow'>
        <td>
          <div class="cart-info">
            <img src="{{c.product.photo.url}}" alt="" />
            <div>
             <a href="{% url 'productdetail' c.product.id %}"> <span style="color: #ff7a0d;font-size: 1.8rem;"><strong>{{c.product.name}}</strong></span><br></a>
              <span>Price: Rs.{{c.product.selling_price}}</span> <br />
            </div>
          </div>
        </td>
        <td>
          <div class="cartbutton" style="justify-content: flex-start;">
            <button data-id="{{c.product.id}}" data-url="{% url 'remove_from_cart' %}" class="minusbutton mb{{c.product.id}}" style="display: flex; align-items: center;justify-content: center;">-</button>
            <span data-id="{{c.product.id}}"class="buttontext bt{{c.product.id}}" style="display: flex;align-items: center;justify-content: center;margin-bottom: 1rem;">{{c.quantity}}</span>
            <button data-id="{{c.product.id}}" data-url="{% url 'add_to_cart' %}" class="plusbutton pb{{c.product.id}}" style="display: flex;align-items: center;justify-content: center;">+</button>
          </div>
        </td>
        <td><input type="hidden" class="subTotals" name="subtotal" data-subtotal='{{c.sub_total}}'> Rs.{{c.sub_total}}</td>
      </tr>
      {% endfor %}
      {% else %}
      <h3>No products in your cart🥺</h3>
      {% if user.is_anonymous %}
      <h3><a style="color: #ff7a0d;" href="{% url 'login' %}">Login</a> or <a style="color: #ff7a0d;" href="{% url 'signup' %}">Signup</a> to add products to your cart😃</h3>
      {% endif %}
      {% endif %}
    </table>
    <div class="total-price">
      <table>
        <tr>
          <td>Total Cost:</td>
          <td class="prodOnlyTotal"></td>
        </tr>
        <!-- <tr>
          <td>Tax</td>
          <td>$50</td>
        </tr>
        <tr>
          <td>Total</td>
          <td>$250</td>
        </tr> -->
      </table>
      {% if user.is_authenticated %}
      <a href="{% url 'checkout' %}" class="checkout btn">Proceed To Checkout</a>
      {% else %}
      <button class="checkout btn" style="cursor: pointer;outline: none;border: none;">Proceed To Checkout</button>
      {% endif %}
    </div>
  </div>

  <!-- Other Products -->
<section class="section featured">
    <div class="top container">
        <h1>Other Products</h1>
        <a href="{% url 'products' %}" class="view-more">View more</a>
    </div>
    <div class="product-center container">
        {% for pro in otherprod %}
        <div class="product-item">
            <div class="overlay">
                <a href="{% url 'productdetail' pro.id %}" class="product-thumb">
                    <img src="{{ pro.photo.url }}" alt="" />
                </a>
                <span class="discount">{{pro.discount_percent}}%</span>
            </div>
            <div class="product-info">
                <span>{{ pro.category.title}}</span>
                <a href="{% url 'productdetail' pro.id %}">{{ pro.name }}</a>
                <h4>Rs. {{ pro.selling_price }}</h4>
                <div class="cartbutton">
                    <a href="{% url 'productdetail' pro.id %}"><button class="quickviewbutton">Quick View</button></a>
                </div>
            </div>
            <ul class="icons">
                <a href="{% url 'productdetail' pro.id %}"><li> Quick View</li></a>
            </ul>
        </div>
        {% endfor %}
    </div>
</section>
{% endblock maincontent %}
{% block jscode %}
<script>
  const subTotals = document.querySelectorAll('.subTotals');
  let total = 0
  subTotals.forEach(element => {
    total +=parseFloat(element.getAttribute('data-subtotal'))
  });
  document.querySelector('.prodOnlyTotal').innerText = 'Rs.'+total+'.0';
  console.log(total)
</script>
{% endblock jscode %}

otpproject/templates/home/checkout.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Checkout{% endblock title %}
{% block maincontent %}
<div class="message-popup select-address-popup">
    <div></div>
    <p>Select or add an address first</p>
    <div class="hide-message-popup">&times;</div>
</div>


<div class="container checkout-container">
    <div class="checkout-products">
        <h2>Order Summary</h2>
        {% for p in cartprod %}
        <div class="checkout-product">
            <img src="{{p.product.photo.url}}" alt="" />
            <div>
                <p><strong>{{p.product.name}}</strong></p>
                <span>Quantity: {{p.quantity}}</span> <br />
                <span><strong>Price:</strong> Rs.{{p.sub_total}}</span> 
                <input type="hidden" name="subTotals" class="subTotals" data-subtotal="{{p.sub_total}}">
            </div>
        </div>
        {% endfor %}
        <h4 class="prodOnlyTotal"></h4>
        <div class="checkout-terms">
            <p style="color: #444;">
                Term and condition: Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nisi dicta corporis ape
                riam vel deleniti dolorum omnis, accusantium iste dolores, ipsum sequi, saepe architecto amet sint qu
            </p>
        </div>
    </div>
    <div class="payment">
        <div class="another-address">
            <button>Add new address</button>
        </div>
        <div class="customer-form">
            <form action="{% url 'checkout' %}" method="post" novalidate>
                <h3>Add New Customer/Address</h3>
                {% csrf_token %}
                {% for fm in form %}
                <i style="color: red;font-style: normal;">{{fm.errors|striptags}}</i> {{fm.label_tag}}
                    {{fm}}
                {% endfor %}
    
                <div class="buttons">
                    <a href="{% url 'home' %}"><button type="button" class="cancelbtn">Cancel</button></a>
                    <button type="submit" class="signupbtn">Add Adress</button>
                </div>
                {% if form.non_field_errors %}
                {% for error in form.non_field_errors %}
                    <p class='form-field-error' style="color: red;">{{error}}</p>
                {% endfor %}
                {% endif %}
            </form>
        </div>
        <form action="{% url 'place_order' %}" method="post">
            {% csrf_token %}
            <h3 style="border-bottom: 1px solid #888;">Select Address</h3>
            {% if customers %}
            {% for c in customers %}
            <div class="address">
                <div class="address-radio">
                    <input type="radio" name="address" id="address" value="{{c.id}}">
                </div>
                <div class="address-desc">
                    <h4>{{c.full_name}}</h4>
                <p>{{c.locality}}, {{c.address}}, {{c.city }} -{% if c.zip_code %}{{c.zip_code}}{% endif %}</p>
                </div>
            </div>
            {% endfor %}
            {% else %}
            <h4 style="padding: 1rem;text-align: center;">No Address Yet</h4>
            {% endif %}
            <div class="payment-option-box">
                <h4>Payment options:</h4>
                <select name="payment-option" id="payment-option">
                    <option value="1">Cash On Delivery</option>
                </select>
            </div>
            {% if customers %}
            <input  type="submit" class="checkout-submit" value="Submit">
            {% else %}
            <input type="submit" class="show-message-popup" value="Submit">
            {% endif %}
        </form>
    </div>
</div>
{% endblock maincontent %}
{% block jscode %}
<script>
    const subTotals = document.querySelectorAll('.subTotals');
    let total = 0
    subTotals.forEach(element => {
      total +=parseFloat(element.getAttribute('data-subtotal'))
    });
    document.querySelector('.prodOnlyTotal').innerText = 'Total cost: Rs.'+total+'.0';
    console.log(total)
  </script>
{% endblock jscode %}

otpproject/templates/home/contact.html
{% extends 'base.html' %}

{% block title %}Contact Page{% endblock title %}
{% block css %}
<style>
    #id_message{
        padding: .5rem;
        font-size: 1.5rem;
    }
</style>
{% endblock css %}
{% block maincontent %} 
<div class="container">
    <div class="login-form">
        <form action="{% url 'contact' %}" method="post" novalidate>
            <h1>Your Message</h1>
            {% csrf_token %}
            {% for fm in form %}
            <i style="color: red;font-style: normal;">{{fm.errors|striptags}}</i> {{fm.label_tag}}
             {{fm}}
            {% endfor %}
            <div class="buttons">
                <a href="{% url 'home' %}"><button type="button" class="cancelbtn">Cancel</button></a>
                <button type="submit" class="signupbtn">Submit</button>
            </div>
            {% if form.non_field_errors %}
            {% for error in form.non_field_errors %}
                <p class='form-field-error' style="color: red;">{{error}}</p>
            {% endfor %}
            {% endif %}
        </form>
    </div>
</div>
{% endblock maincontent %}

otpproject/templates/home/orders.html
{% extends 'base.html' %}
{% load static %}
{% block title %}My Orders{% endblock title %}
{% block maincontent %}
<div class="container cart" style="padding: 0;">
    <table>
      <tr id='carttablerow'>
        <th>Product</th>
        <th>Quantity</th>
        <th>Cost</th>
        <th style="text-align: center;">Order Status</th>
      </tr>
      {% if orders %}
      {% for o in orders %}
      <tr style="border-bottom: 1px solid rgb(233, 233, 233);">
        <td>
          <div class="cart-info">
            <img src="{{o.product.photo.url}}" alt="" />
            <div>
              <span><a href="{% url 'productdetail' o.product.id %}" style="color: #ff7a0d;font-size: 17px;">{{o.product.name}}</a></span> <br />
              <span>Price: Rs.{{o.product.selling_price}}</span>
            </div>
          </div>
        </td>
        <td>
          <p style="font-weight: 500;">{{o.quantity}}</p>
        </td>
        <td><p style="color: #ff7a0d;">Rs.{{o.total_price}}.0</p></td>
        <td class="order-status">
          {% if o.order_status == 'pending' %}
          <p><span class="span-status">Pending</span></p>
          <p><span class="span-percentage pending"><span class="percent">20%</span></span></p>
          {% elif o.order_status == 'received' %}
          <p><span class="span-status">Received</span></p>
          <p><span class="span-percentage received"><span class="percent">40%</span></span></p>
          {% elif o.order_status == 'packed' %}
          <p><span class="span-status">Packed</span></p>
          <p><span class="span-percentage packed"><span class="percent">60%</span></span></p>
          {% elif o.order_status == 'on_the_way' %}
          <p><span class="span-status">On The Way</span></p>
          <p><span class="span-percentage ontheway"><span class="percent">80%</span></span></p>
          {% elif o.order_status == 'delivered' %}
          <p><span class="span-status">Delivered</span></p>
          <p><span class="span-percentage delivered"><span class="percent">100%</span></span></p>
          {% else %}
          {% endif %}
        </td>
      </tr>
      {% endfor %}
      {% else %}
      <h3>No orders are placed yet🥺</h3>
      {% if user.is_anonymous %}
        <h3><a style="color: #ff7a0d;" href="{% url 'login' %}">Login</a> or <a style="color: #ff7a0d;" href="{% url 'signup' %}">Signup</a> to place orders😃</h3>
        {% endif %}
      {% endif %}
    </table>
  </div>

{% endblock maincontent %}
{% block jscode %}
{% endblock jscode %}

otpproject/templates/home/terms.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Terms & Conditions | Bake Yummy!{% endblock title %}
{% block maincontent %}
<section class="terms">
    <div class="termsimage">
        <h1>TERMS & CONDITIONS</h1>
    </div>
    <div class="termstext">
        <ul class="points">
            <li>Get a flat 10% discount by signing up and registering on the platform.</li>
            <li>Goods once sold won't be returned.</li>
            <li>In case you change your mind to not buy the product after it is dispatched for delivery, we will charge you the delivery fees which is NRs. 100 for inside Kathmandu valley and Rs. 200 for outside the valley.</li>
            <li>There is so much effort we put forth for creating order, packaging and delivery. So, unless you aren't serious about the order, please feel free to not order in the first place.</li>
        </ul>
    </div>
</section>
{% endblock maincontent %}